### ISSUE TITLE
non-ASCII characters are garbled

### ISSUE THREAD

**Issue by ufcpp** [SteveSandersonMS/dotnet-wasi-sdk#1]
## Version Used

Windows 11 (current culture: ja-JP)
.NET SDK 7.0.100-preview.2.22153.17
Wasi.Sdk 0.1.0

## Step to repro

```cs
Console.WriteLine("a α Я あ");
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Wasi.Sdk" Version="0.1.0" />
  </ItemGroup>

</Project>
```

Run with

* both Windows Console Host and Windows Terminal
* both F5 in Visual Studio and `wasmtime app.wasm` in the terminal

## Expected result

```
a α Я あ
```

## Actual result

```
a ﾎｱ ﾐｯ 縺・
```

This output seems like a string written "a α Я あ" as UTF-8 and read as Shift_JIS (code page 932). CP932 is a default encoding for Windows ja-JP.

On the other hands, if you run the wasm on WebAssembly.sh, there is no characters garbled.

![image](https://user-images.githubusercontent.com/3760955/160839950-bc1dac35-bf58-42fa-99f7-98dcc91df73a.png)

**Comment by ufcpp** [comment]
Ah, chcp 650001 solves the issue.

```
>chcp 65001
Active code page: 65001

>wasmtime WasiSdkConsole1.wasm
a α Я あ
```

**Comment by SteveSandersonMS** [comment]
Cool, thanks for letting us know! So it looks like an issue in the terminal emulator, not in this project.
