### ISSUE TITLE
.nuget Wasi.Sdk.targets issues in windows resolving paths when "UserProfile" has spaces

### ISSUE THREAD

**Issue by juanfranblanco** [SteveSandersonMS/dotnet-wasi-sdk#14]
If user name has spaces in her name, the files needed for compilation cannot be resolved in the nuget folder.
This is a quick workaround:
https://gist.github.com/juanfranblanco/caf8c0bec81f0aa1895cae01911aa742

https://gist.github.com/juanfranblanco/15a0f67bcc29a9d8bae7b04cd225fa37

**Comment by SteveSandersonMS** [comment]
Thanks @juanfranblanco. I've applied some fixes. It's a smaller set of changes than in your proposal but I think it should work. If you still have trouble please let me know!
