### ISSUE TITLE
Can I use this to run a dotnet core WPF app on linux?

### ISSUE THREAD

**Issue by sam-wheat** [SteveSandersonMS/dotnet-wasi-sdk#15]
Should I?
How?
App need to access MySQL.

Thanks

**Comment by marinasundstrom** [comment]
No. This project will not enable you to run a Windows-based technology such as WPF on Linux. And there is not support for MySQL, at least now.

Think of WebAssembly as its own operating environment - a virtual machine. WASI (System Interface) gives you secure access to some common services of the host, filesystem access and networking, may it be on Windows, macOS or on Linux. 

The Windows-specific libraries required by WPF can't be accessed from WASM via WASI - nor do they exist on maxOS or Linux anyway. 

I would suggest checking out Avalonia as a cross-platform substitute for WPF. It is a community project targeting multiple platforms, such as Linux and Android.

**Comment by geodeasic** [comment]
Also check out .NET MAUI.
