### ISSUE TITLE
WASI as a Runtime Identifier

### ISSUE THREAD

**Issue by ladeak** [SteveSandersonMS/dotnet-wasi-sdk#17]
Question:

Looking at how ASP.NET Core server has been implemented, wouldn't it make more sense to have .net runtime target WASI? So when someone builds and published an app, next to linux, win, etc RIDs have wasi too?

I suppose this would be a considerable investment though.

**Comment by SteveSandersonMS** [comment]
Yes, something like that sounds right to me. We already have a `browser-wasm` RID so a `wasi-wasm` one would make sense alongside that.

**Comment by ladeak** [comment]
Thanks for the answer.
