### ISSUE TITLE
Is it possible to selectively export classes or static methods in the built .wasm file that can be invoked directly?

### ISSUE THREAD

**Issue by jlgaffney** [SteveSandersonMS/dotnet-wasi-sdk#19]
I'd like to be able to build a .wasm file from a class library without an entrypoint and expose certain classes or static methods that can be invoked with arguments, to then potentially use in the browser or other environments.

Is this currently possible? If not can arguments be passed into the Main method as a potential alternative?

**Comment by SteveSandersonMS** [comment]
Agreed, we should make this straightforwards to do. I think https://github.com/SteveSandersonMS/dotnet-wasi-sdk/issues/30 will cover this.
