### ISSUE TITLE
Can the generated wasm be run in a browser ?

### ISSUE THREAD

**Issue by bogdancucosel** [SteveSandersonMS/dotnet-wasi-sdk#23]
Hi!

First of all , great work on this.
It is not clear for me, since this is a wasi sdk, is it supposed to also be able to run in a browser ?
I tried something like:

	<script>
		const importObject = {
			module: {},
			env: {
			memory: new WebAssembly.Memory({ initial: 256 }),
			}
		};
		fetch('test-wasm.wasm')
		.then(response =>
        	response.arrayBuffer())
		.then(bytes =>
        	WebAssembly.instantiate(bytes, importObject))
		.then(results => {
			const Answer = results.instance.exports.Answer;
			console.log(Answer());
		}, error => {
			console.log(error);
		});		
	</script>

But I get "TypeError: WebAssembly.instantiate(): Import #0 module="wasi_snapshot_preview1" error: module is not an object or function"

Thank you very much

**Comment by marinasundstrom** [comment]
No, browsers does not implement WASI since it cannot access the host system directly. 

But there are polyfills for that replace that functionality by invoking browser APIs - JS APIs.

**Comment by bogdancucosel** [comment]
Thanks for the answer.
I see now, so basically I would need polyfills for the functions that are imported in the compiled wasi, right ?.
![image](https://user-images.githubusercontent.com/35687412/176107603-8fed8798-a0ab-42a8-9710-db0501b5787e.png)

Is there somewhere I could grab these polyfills ?

Thank you again

**Comment by lbguilherme** [comment]
@bogdancucosel This is what you are looking for: https://github.com/wasmerio/wasmer-js

**Comment by bogdancucosel** [comment]
@lbguilherme thanks a lot, I will try it
