### ISSUE TITLE
More Aggressive Trimming

### ISSUE THREAD

**Issue by stevefan1999-personal** [SteveSandersonMS/dotnet-wasi-sdk#24]
It seems like the smallest hello world example I can produce here has a final artifact size of 15MB, and 6MB after aggressive `wasm-opt`, and 2MB after compression, which is still overwhelmingly huge to fit in the 1MB limit of Cloudflare Workers. So I was looking for more trimming opportunities, for example, would removing I18N help this kind of situation?

**Comment by JeepNL** [comment]
Just FYI, I read this tweet just now on Twitter. I don't know if this has anything to do with the size, I'm just sharing it here.

"Announcing support for WASI on Cloudflare Workers"

👉 https://blog.cloudflare.com/announcing-wasi-on-workers/

**Comment by stevefan1999-personal** [comment]
> [UPDATE: Oops: I see it's a post from 7/7 - it's probably what you were talking about ..]
> 
> Just FYI, I read this tweet just now on Twitter. I don't know if this has anything to do with the size, I'm just sharing it here.
> 
> "Announcing support for WASI on Cloudflare Workers"
> 
> 👉 https://blog.cloudflare.com/announcing-wasi-on-workers/

Exactly. But the 1MB restriction still applies. I have already been able to run .NET WASI in local dev mode.
