### ISSUE TITLE
Unable to run / debug AspNet Core API

### ISSUE THREAD

**Issue by TopSwagCode** [SteveSandersonMS/dotnet-wasi-sdk#25]
Hi. When I try to run Console WASM I can run it without problems. But following your guide on AspNet Core example I run into the following:
 
Startup from visual studio:

The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[20796] wasmtime.exe' has exited with code 1 (0x1).

Startup from Terminal:

`Method not found: bool System.Net.Quic.QuicListener.get_IsSupported()`

I am running on: 
7.0.100-preview.6.22352.1
wasmtime-cli 0.38.1

**Comment by TopSwagCode** [comment]
> @TopSwagCode I had the same issue, but when I downgraded to the earlier preiview release of dotnet: `7.0.100-preview.4.22252.9` I managed to run the web app example.

Thank you. After a bit of problems uninstalling preview and installing old one it works :D

**Comment by SteveSandersonMS** [comment]
Thanks for reporting this.

The latest version, https://www.nuget.org/packages/Wasi.Sdk/0.1.2-preview.10061, works with the latest SDKs. So it should no longer be necessary to downgrade your SDK.
