### ISSUE TITLE
Thoughts on startup latency

### ISSUE THREAD

**Issue by dicej** [SteveSandersonMS/dotnet-wasi-sdk#34]
I've been experimenting with profiling and optimizing a simple C# app compiled to Wasm using this SDK, and I'd like to report my findings here and brainstorm next steps.

The app in question is a FaaS-style HTTP request handler which simply returns "hello, world" to every request.  I've been running this app using [Spin](https://github.com/fermyon/spin), which is based on Wasmtime.  For security and determinism, Spin creates a new instance for each request, using Wasmtime's `instantiate_pre` function to minimize overhead (i.e. avoid compiling the same module to native machine code more than once).

Using the unmodified Wasm output from the SDK, each request takes about 60-70ms to complete.  With [Wizer](https://github.com/bytecodealliance/wizer) we can improve that by 10x to around 6-7ms.  If you're not already familiar with Wizer, it runs a module's initialization function at build time and uses a snapshot of its global variables and non-zero memory regions to produce a new module which does not require runtime initialization.

What's interesting is that the request handling function itself only takes about half a millisecond to run.  The rest of the time is spent instantiating the module -- specifically `memmove`'ing the `data` segments generated by Wizer into the instance's runtime memory.  (See [here](https://github.com/bytecodealliance/wasmtime/blob/6368c6b1881462e500e4bed3d66631440afb63aa/crates/runtime/src/instance/allocator.rs#L357-L384) for the code that dominated the profiles if interested.)

One of the things I noticed was that Wizer was creating a very large number of `data` segments for the app: 55,365 to be exact.  This seems to be due to (A) the .NET runtime touching a lot of memory at startup and (B) Wizer creating a separate `data` segment for each non-zero region delimited by a run of at least 4 zeros.  On a hunch, I hacked Wizer to consolidate these segments by requiring a run of at least 128 zeros between segments.  That brought the segment count down to 778 and improved performance by about 15%.  I tried other numbers, too, but never got much better than a 15% improvement.

My conclusion is that there's not a lot of room for improvement on the Wizer side, so that leaves either the .NET runtime or Wasmtime (or both).  Of the two, I'm more familiar with Wasmtime, and I have some ideas about how to move those `memmove`s to pre-instantiation which may or may not work.  In the meantime, I wanted to check here to find out if anything could be done on the .NET side, e.g. to reduce the amount of memory that needs to be initialized for simple apps, or to do some kind of compacting GC at the end of initialization.  Even if the answer is just: "there's nothing left to be done on the .NET side -- it is what it is", that would be good to know, in which case I'll focus my efforts on the Wasmtime side.

Thanks!

**Comment by dicej** [comment]
Update: I was able to get sub-millisecond latencies by setting [`memory_guaranteed_dense_image_size`](https://docs.rs/wasmtime/latest/wasmtime/struct.Config.html#method.memory_guaranteed_dense_image_size) to 1GB in Wasmtime.  That results in a large, 500MB+ .cwasm file, but presumably it will shrink down to ~50MB once we've updated to the latest SDK, per https://github.com/SteveSandersonMS/dotnet-wasi-sdk/issues/11#issuecomment-1207839328.

Anyway, I consider this solved, so I'll close the issue.

**Comment by dicej** [comment]
One more note: `fallocate -d <cwasm>` will bring actual disk usage of the .cwasm file down to 26MB by making it a sparse file.

**Comment by ChristianWeyer** [comment]
Do you have a sample or instructions on how to use wizer with your C# code @dicej ?

**Comment by dicej** [comment]
@ChristianWeyer Check out https://github.com/fermyon/spin-dotnet-sdk, specifically https://github.com/fermyon/spin-dotnet-sdk/blob/0b320bad3c661bb2d3af5950f1b76af8f7fb655d/src/native/http-trigger.c#L119-L145 and https://github.com/fermyon/spin-dotnet-sdk/blob/0b320bad3c661bb2d3af5950f1b76af8f7fb655d/src/build/Fermyon.Spin.Sdk.targets#L19.

Also note that Wizer can sometimes expose bugs in the .NET WASI SDK, leading to "out of bounds" memory errors (e.g. https://github.com/fermyon/spin-dotnet-sdk/pull/34).  Your mileage may vary.
